import { useState, useRef } from 'react';
import { Link } from 'react-router-dom';
import { verifyByPDF } from '../api';

export default function VerifierDashboard() {
  const [file, setFile]         = useState(null);
  const [loading, setLoading]   = useState(false);
  const [result, setResult]     = useState(null);
  const [error, setError]       = useState('');
  const [dragOver, setDragOver] = useState(false);
  const inputRef = useRef();

  const handleFile = (f) => {
    if (!f) return;
    if (f.type !== 'application/pdf') { setError('Please upload a PDF file only'); return; }
    setFile(f); setResult(null); setError('');
  };

  const handleDrop = (e) => {
    e.preventDefault(); setDragOver(false);
    handleFile(e.dataTransfer.files[0]);
  };

  const handleVerify = async () => {
    if (!file) return;
    setLoading(true); setResult(null); setError('');
    try {
      const data = await verifyByPDF(file);
      setResult(data);
    } catch (e) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setFile(null); setResult(null); setError('');
    if (inputRef.current) inputRef.current.value = '';
  };

  const isValid   = result && (result.valid === true  || result.status === 'ACTIVE');
  const isRevoked = result && (result.status === 'REVOKED');
  const isInvalid = result && (result.valid === false && result.status !== 'REVOKED');

  return (
    <div className="verify-page">
      {/* Header */}
      <div className="verify-header">
        <div className="brand">CertChain</div>
        <div style={{ display: 'flex', alignItems: 'center', gap: 16 }}>
          <span style={{ fontSize: 12, color: 'var(--white-dim)' }}>Public Certificate Verifier — No login required</span>
          <Link to="/login" className="btn btn-ghost btn-sm">Sign In →</Link>
        </div>
      </div>

      {/* Body */}
      <div className="verify-body">
        <div className="verify-box">
          <div style={{ textAlign: 'center', marginBottom: 36 }}>
            <div style={{ fontFamily: 'Playfair Display, serif', fontSize: 32, color: 'var(--white)', marginBottom: 8 }}>
              Verify a Certificate
            </div>
            <p style={{ fontSize: 14, color: 'var(--white-dim)', maxWidth: 360, margin: '0 auto', lineHeight: 1.6 }}>
              Upload any certificate PDF issued by this system. The QR code will be scanned and verified against the blockchain instantly.
            </p>
          </div>

          {/* Upload zone */}
          {!result && (
            <div
              className={`file-drop ${dragOver ? 'drag-over' : ''}`}
              onDragOver={e => { e.preventDefault(); setDragOver(true); }}
              onDragLeave={() => setDragOver(false)}
              onDrop={handleDrop}
              onClick={() => inputRef.current.click()}
              style={{ cursor: 'pointer' }}
            >
              <input
                ref={inputRef}
                type="file"
                accept="application/pdf"
                style={{ display: 'none' }}
                onChange={e => handleFile(e.target.files[0])}
              />
              <div className="file-drop-icon">{file ? '📄' : '⬆'}</div>
              <div className="file-drop-text">
                {file ? file.name : 'Drop certificate PDF here or click to browse'}
              </div>
              <div className="file-drop-hint">Only PDF files generated by this system will be accepted</div>
            </div>
          )}

          {error && (
            <div className="alert alert-error" style={{ marginTop: 16 }}>
              {error}
              <button className="btn btn-ghost btn-sm" style={{ marginLeft: 'auto' }} onClick={() => setError('')}>✕</button>
            </div>
          )}

          {/* Action buttons */}
          {!result && (
            <div style={{ display: 'flex', gap: 10, marginTop: 16 }}>
              <button
                className="btn btn-primary btn-full btn-lg"
                onClick={handleVerify}
                disabled={!file || loading}
              >
                {loading
                  ? <><span className="spinner" /> Scanning QR &amp; verifying blockchain...</>
                  : '🔍 Verify Certificate'}
              </button>
              {file && <button className="btn btn-ghost" onClick={reset}>✕</button>}
            </div>
          )}

          {/* Result */}
          {result && (
            <div className="verify-result" style={{
              borderLeft: `4px solid ${isValid ? 'var(--green)' : 'var(--red)'}`
            }}>
              {/* Result header */}
              <div style={{ display: 'flex', alignItems: 'center', gap: 14, marginBottom: 20 }}>
                <div style={{
                  width: 52, height: 52,
                  borderRadius: '50%',
                  background: isValid ? 'var(--green-dim)' : 'var(--red-dim)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  fontSize: 22, flexShrink: 0
                }}>
                  {isValid ? '✓' : isRevoked ? '⊘' : '✗'}
                </div>
                <div>
                  <div style={{
                    fontFamily: 'Playfair Display, serif',
                    fontSize: 20,
                    color: isValid ? 'var(--green)' : 'var(--red)'
                  }}>
                    {isValid ? 'Certificate is Authentic'
                     : isRevoked ? 'Certificate has been Revoked'
                     : 'Certificate is Invalid'}
                  </div>
                  <div style={{ fontSize: 12, color: 'var(--white-dim)', marginTop: 3 }}>
                    {isValid
                      ? 'This certificate is recorded on the blockchain and has not been tampered with.'
                      : isRevoked
                      ? 'This certificate was revoked by the issuing organization and is no longer valid.'
                      : 'This certificate could not be verified against the blockchain.'}
                  </div>
                </div>
              </div>

              <div className="divider" />

              {/* Scanned details */}
              {result.scannedCertificate && (
                <>
                  <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 1.5, color: 'var(--white-dim)', marginBottom: 12 }}>
                    Scanned Certificate Details
                  </div>
                  {[
                    { label: 'Certificate ID', val: result.scannedCertificate.certId },
                    { label: 'Issuer',         val: result.scannedCertificate.issuer },
                    { label: 'Recipient',      val: result.scannedCertificate.recipient },
                    { label: 'Blockchain Hash',val: result.scannedCertificate.hash, mono: true },
                  ].filter(r => r.val).map(row => (
                    <div key={row.label} style={{
                      display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                      padding: '10px 12px', background: 'var(--navy-3)', borderRadius: 6,
                      marginBottom: 6, gap: 12
                    }}>
                      <span style={{ fontSize: 11, color: 'var(--white-dim)', fontWeight: 600, flexShrink: 0 }}>{row.label}</span>
                      <span style={{
                        fontSize: row.mono ? 10 : 13,
                        color: 'var(--white)',
                        fontFamily: row.mono ? 'DM Mono, monospace' : undefined,
                        textAlign: 'right', wordBreak: 'break-all'
                      }}>
                        {row.mono && row.val ? row.val.slice(0, 48) + '…' : row.val}
                      </span>
                    </div>
                  ))}
                </>
              )}

              <div style={{ marginTop: 16, display: 'flex', gap: 10 }}>
                <button className="btn btn-ghost btn-full" onClick={reset}>Verify Another</button>
              </div>
            </div>
          )}

          {/* How it works */}
          {!result && !file && (
            <div style={{ marginTop: 40 }}>
              <div style={{ fontSize: 10, fontWeight: 600, textTransform: 'uppercase', letterSpacing: 2, color: 'var(--white-dim)', textAlign: 'center', marginBottom: 20 }}>
                How Verification Works
              </div>
              <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                {[
                  ['1', 'Upload the certificate PDF',      'The QR code embedded in the certificate is scanned automatically'],
                  ['2', 'QR data is extracted',            'Certificate ID and SHA-256 hash are read from the QR code'],
                  ['3', 'Blockchain query',                 'The hash is verified against the immutable Hyperledger Fabric ledger'],
                  ['4', 'Instant result',                  'You instantly know if the certificate is authentic, revoked, or forged'],
                ].map(([n, title, desc]) => (
                  <div key={n} style={{
                    display: 'flex', gap: 14, padding: '14px 16px',
                    background: 'var(--navy-2)', borderRadius: 8,
                    border: '1px solid rgba(255,255,255,0.05)'
                  }}>
                    <div style={{
                      width: 28, height: 28, borderRadius: '50%',
                      background: 'var(--gold-dim)', border: '1px solid var(--gold-border)',
                      display: 'flex', alignItems: 'center', justifyContent: 'center',
                      color: 'var(--gold)', fontSize: 12, fontWeight: 700, flexShrink: 0
                    }}>{n}</div>
                    <div>
                      <div style={{ fontSize: 13, fontWeight: 600, color: 'var(--white)' }}>{title}</div>
                      <div style={{ fontSize: 11, color: 'var(--white-dim)', marginTop: 2 }}>{desc}</div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}