const { fromBuffer } = require('pdf2pic');
const Jimp = require('jimp');
const jsQR = require('jsqr');

const extractQRFromPDF = async (pdfBuffer) => {
    const converter = fromBuffer(pdfBuffer, {
        density: 200,
        format: 'png',
        width: 2384,
        height: 1684,
        preserveAspectRatio: true,
        saveFilename: 'qrscan',
        savePath: '/tmp'
    });

    let pageResult;
    try {
        pageResult = await converter(1, { responseType: 'buffer' });
    } catch (e) {
        throw new Error(`Failed to render PDF page: ${e.message}`);
    }

    if (!pageResult || !pageResult.buffer) {
        throw new Error('PDF rendering returned no data. Ensure ghostscript and graphicsmagick are installed.');
    }

    // ── Jimp v0.x API ─────────────────────────────────────────────
    let image;
    try {
        image = await new Promise((resolve, reject) => {
            Jimp.read(pageResult.buffer, (err, img) => {
                if (err) reject(err);
                else resolve(img);
            });
        });
    } catch (e) {
        throw new Error(`Failed to decode rendered image: ${e.message}`);
    }

    const { data, width, height } = image.bitmap;

    const code = jsQR(new Uint8ClampedArray(data), width, height, {
        inversionAttempts: 'attemptBoth'
    });

    if (!code) {
        throw new Error(
            'No QR code detected in the uploaded PDF. ' +
            'Ensure the PDF was generated by this system and is not corrupted.'
        );
    }

    let payload;
    try {
        payload = JSON.parse(code.data);
    } catch {
        throw new Error(`QR code found but data is not valid JSON. Raw: "${code.data.substring(0, 80)}"`);
    }

    if (!payload.certId || !payload.hash) {
        throw new Error('QR payload is missing certId or hash fields.');
    }

    return payload;
};

module.exports = { extractQRFromPDF };
